package com.riigsoft.security.controller;

import com.riigsoft.security.entity.User;
import com.riigsoft.security.request.UserRequest;
import com.riigsoft.security.response.UserResponse;
import com.riigsoft.security.service.IUserService;
import com.riigsoft.security.util.JwtUtil;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.security.Principal;

@RestController
@RequestMapping("/user")
public class UserController {

    @Autowired
    private IUserService service;
    @Autowired
    private JwtUtil util;
    @Autowired
    private AuthenticationManager authenticationManager;

    //1. save User data in database
    @PostMapping("/save")
    public ResponseEntity<String> saveUser(@RequestBody User user){
        Integer id = service.saveUser(user);
        String body ="User '"+id+"' saved.";
        //return new ResponseEntity<String>(body,HttpStatus.OK);
        return ResponseEntity.ok(body);
    }

    //2. validate user and generate token(login)
    @PostMapping("/login")
    public ResponseEntity<UserResponse>loginUser(@RequestBody UserRequest request){

        //validate user and password with database
        authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(
                        request.getUsername(),
                        request.getPassword()
                ));

        String token = util.generateToken(request.getUsername());
        return ResponseEntity.ok(new UserResponse(token,"Success! Generated by Raghu."));
    }

    //3. After login only

    @PostMapping("/welcome")
    public ResponseEntity<String>accessData(Principal p){

        return ResponseEntity.ok("Hello User "+p.getName());
    }


}
